replicaCount: 1
image:
  repository: 378784712135.dkr.ecr.us-east-1.amazonaws.com/frontend
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  annotations: {}
  name: "frontend"

service:
  type: ClusterIP
  port: 80
  containerPort: 8080

resources:
   limits:
     cpu: 100m
     memory: 256Mi
   requests:
     cpu: 100m
     memory: 256Mi

env:
  name: dev

configmap:
  create: true
  content:
    roboshop.conf: |
      proxy_http_version 1.1;
      location /images/ {
          expires 5s;
          root   /usr/share/nginx/html;
          try_files $uri /images/placeholder.jpg;
      }
      error_page   500 502 503 504  /50x.html;
      location /api/catalogue/ { proxy_pass http://catalogue-dev:80/; }
      location /api/user/ { proxy_pass http://user-dev:80/; }
      location /api/cart/ { proxy_pass http://cart-dev:80/; }
      location /api/shipping/ { proxy_pass http://shipping-dev:80/; }
      location /api/payment/ { proxy_pass http://payment-dev:80/; }
      location /health {
              return 200 'OK';
          }
      location /nginx_status {
          stub_status on;
          access_log off;
      }